export interface BlogPost {
  slug: string
  title: string
  description: string
  date: string
  dateModified: string
  category: string
  keywords: string[]
  image: string
  readTime: string
  content: string[]
}

export const blogPosts: BlogPost[] = [
  {
    slug: "computer-vision-hull-inspection",
    title: "How computer vision is revolutionizing hull damage detection in cargo ships",
    description:
      "Learn how AI-powered computer vision detects hull damage across structural zones, replacing weeks-long manual inspections with instant, standardized analysis.",
    date: "2025-03-05",
    dateModified: "2026-05-01",
    category: "Computer Vision",
    keywords: ["hull damage detection AI", "computer vision ship inspection", "cargo vessel hull analysis"],
    image:
      "https://res.cloudinary.com/drasbgjxe/image/upload/q_auto/f_auto/v1776652498/cargo-vision-inspection_yhxpc7.jpg",
    readTime: "6 min read",
    content: [
      "## The Problem with Traditional Hull Inspection",
      "For decades, marine hull inspection has relied on the same process: a surveyor boards the vessel, walks the deck, and documents what they see. The output is a PDF report — subjective, inconsistent, and typically weeks old by the time it reaches an underwriter's desk.",
      "This matters because hull condition is the single largest factor in marine insurance risk assessment. A vessel with undetected corrosion, osmotic blistering, or structural fatigue represents millions in potential claims exposure. Yet the industry's inspection methodology has barely changed since the 1970s.",
      "The numbers tell the story: 40% of marine insurance claims face documentation disputes. Not because the claims are fraudulent, but because the baseline condition data simply does not exist in a standardized, verifiable format.",
      "## How Computer Vision Changes the Equation",
      "Computer vision applies the same pattern recognition capabilities that power autonomous vehicles and medical imaging to the problem of vessel inspection. The technology analyzes photographs of a vessel and identifies damage patterns that human inspectors might miss — or document inconsistently.",
      "The process works in three stages:",
      "**Stage 1: Zone Mapping.** The system identifies the vessel type and maps structural zones — hull below waterline, hull above waterline, deck, superstructure, fittings, and machinery spaces. Each zone has different damage patterns and risk implications.",
      "**Stage 2: Damage Detection.** Within each zone, the AI analyzes for specific damage types: corrosion (surface and deep pitting), osmotic blistering, impact damage, coating failure, weld deterioration, and structural deformation. Each finding is classified by type, severity, and extent.",
      "**Stage 3: Structured Output.** Unlike a traditional survey report, the output is structured data — machine-readable findings with severity ratings, confidence scores, and precise location mapping. This data feeds directly into condition scoring and underwriting systems.",
      "## Accuracy vs. Human Inspectors",
      "The question insurers ask first: is it accurate? The evidence is compelling.",
      "In controlled comparisons, AI-powered hull analysis detects 15-20% more surface-level damage than manual inspection. The reason is consistency, not intelligence. A human surveyor's attention varies with fatigue, weather conditions, access limitations, and time pressure. The algorithm applies the same detection criteria to every square meter of hull surface.",
      "Where human expertise still wins is in contextual judgment — understanding whether a particular finding is structurally significant or cosmetic. This is why the most effective approach is hybrid: AI handles detection and classification, while deterministic rules handle risk assessment and compliance checking.",
      "## What This Means for Marine Insurance",
      "The implications for the marine insurance value chain are structural:",
      "**For underwriters:** Risk assessment based on verified, current vessel condition data instead of broker summaries and outdated survey reports. Premiums can reflect actual risk, not estimated risk.",
      "**For brokers:** Faster placement cycles. A structured vessel condition report accelerates the submission-to-quote process from weeks to days.",
      "**For vessel owners:** Fair pricing based on actual vessel condition. Well-maintained vessels get the premiums they deserve.",
      "**For claims teams:** Pre-loss baseline documentation that makes claims adjustment faster, fairer, and less adversarial.",
      "## The Bigger Picture",
      "Hull damage detection is the entry point, not the destination. When vessel condition data is captured in a structured, standardized format, it becomes the foundation for an entirely new approach to marine underwriting — one where every decision is traceable, repeatable, and defensible.",
      "The technology exists today. The question is not whether marine insurance will adopt computer vision for hull inspection, but how quickly the industry moves from pilots to production.",
    ],
  },
  {
    slug: "ai-vessel-condition-scoring",
    title: "Vessel condition scoring: how AI outperforms traditional maritime surveys",
    description:
      "Discover how automated vessel condition scoring delivers consistent, repeatable assessments against 47+ maritime standards — eliminating survey subjectivity.",
    date: "2025-03-05",
    dateModified: "2026-05-01",
    category: "Maritime AI",
    keywords: ["vessel condition scoring", "maritime survey automation", "AI vessel assessment"],
    image:
      "https://res.cloudinary.com/drasbgjxe/image/upload/q_auto/f_auto/v1776652504/vessel-ai-assessment_dyupaw.jpg",
    readTime: "7 min read",
    content: [
      "## Why Traditional Surveys Fall Short",
      "Marine surveying is one of the oldest professions in the insurance industry. Classification societies, independent surveyors, and P&I club inspectors have assessed vessel condition for centuries. The methodology is proven. The problem is not competence — it is consistency.",
      "Ask two experienced surveyors to inspect the same vessel on the same day, and you will get two different reports. Different terminology. Different severity assessments. Different recommendations. This is not a failure of skill — it is an inherent limitation of subjective, narrative-based reporting.",
      "For an underwriter trying to price risk accurately, this inconsistency creates a fundamental problem: the data feeding the pricing decision varies based on who collected it, not on the actual condition of the vessel.",
      "## The Scoring Framework",
      "Automated vessel condition scoring replaces narrative assessment with structured, quantitative output. The framework operates at three levels:",
      "**Component Level:** Every structural component — hull plating, deck surfaces, coating systems, through-hulls, machinery mounts — receives an individual condition score. The score reflects the severity, extent, and type of damage detected, measured against defined thresholds.",
      "**Standard Level:** Each component score is checked against relevant maritime standards. SOLAS structural requirements, MARPOL environmental compliance, ABYC recreational vessel standards, and classification society rules each define what constitutes acceptable condition for specific components.",
      "**Vessel Level:** Component scores aggregate into a composite vessel condition score. The aggregation is weighted — hull integrity carries more weight than cosmetic deck condition, for example — reflecting the actual risk hierarchy.",
      "## 47+ Standards, One Assessment",
      "The scale of the compliance challenge in maritime insurance is often underestimated. A single vessel may need to comply with:",
      "- **SOLAS** (Safety of Life at Sea) — structural integrity, fire safety, life-saving equipment\n- **MARPOL** (Marine Pollution) — environmental compliance, discharge systems, fuel containment\n- **ABYC** (American Boat and Yacht Council) — electrical systems, fuel systems, ventilation\n- **Classification society rules** — Lloyd's, DNV, Bureau Veritas, ABS — each with their own structural standards\n- **Flag state requirements** — varying by registration jurisdiction",
      "Checking a vessel against all applicable standards manually is a multi-day exercise. Automated scoring runs the full compliance check in minutes, flagging specific violations with references to the relevant standard clause.",
      "## Repeatability: The Underwriter's Best Friend",
      "The defining advantage of automated scoring is not speed — it is repeatability. When two assessments of the same vessel produce the same score, underwriters can trust the data. When they produce different scores, it means something actually changed.",
      "This repeatability enables capabilities that are impossible with subjective surveys:",
      "**Trend detection:** Track how a vessel's condition changes over time. A declining score flags emerging risk before it becomes a claim.",
      "**Portfolio analysis:** Compare condition scores across a fleet or book of business. Identify outliers and concentration risks.",
      "**Pricing calibration:** When condition data is consistent, pricing models can be calibrated against claims outcomes. The feedback loop between condition → premium → claims becomes measurable.",
      "## The Hybrid Approach",
      "Effective condition scoring does not replace human expertise. It augments it. The optimal architecture is hybrid:",
      "- **AI handles detection and measurement** — identifying damage, classifying severity, checking standards compliance\n- **Deterministic rules handle scoring** — converting findings into quantitative scores using defined methodologies\n- **Human experts handle exceptions** — reviewing edge cases, validating novel findings, updating scoring criteria",
      "This separation matters for regulatory acceptance. When a regulator or auditor asks how a score was derived, every step in the process is documented, traceable, and reproducible.",
      "## From Scoring to Underwriting",
      "Condition scoring is not an end in itself. It is the connective layer between physical inspection and financial decision-making. A vessel condition score becomes an input to valuation models, pricing engines, and claims baseline systems.",
      "The industry's transition from narrative surveys to structured scoring is not a question of technology adoption. It is a question of data infrastructure. The insurers who build this infrastructure first will price risk more accurately, settle claims faster, and retain better books of business.",
    ],
  },
  {
    slug: "instant-ship-insurance-premiums",
    title: "From ship photo to policy: the future of instant vessel insurance premiums",
    description:
      "How AI-driven automation is compressing the marine insurance binding cycle from weeks to minutes — from vessel photo to calculated premium.",
    date: "2025-03-05",
    dateModified: "2026-05-01",
    category: "InsurTech",
    keywords: ["instant vessel insurance", "marine insurance automation", "ship photo to policy"],
    image:
      "https://res.cloudinary.com/drasbgjxe/image/upload/q_auto/f_auto/v1776652498/cargo-insurance-app_pgd9ga.jpg",
    readTime: "6 min read",
    content: [
      "## The 3-6 Week Problem",
      "Binding a marine insurance policy today takes 3 to 6 weeks. The process involves broker submissions, survey scheduling, report generation, underwriter review, quote negotiation, and documentation. Each step introduces delay, manual effort, and data re-entry.",
      "For a $34 billion global premium pool, this inefficiency is not a minor inconvenience. It is a structural cost that affects every participant in the value chain:",
      "- **Vessel owners** wait weeks for coverage, sometimes operating without adequate insurance during the gap\n- **Brokers** spend hours assembling submissions and chasing updates\n- **Underwriters** review the same types of information repeatedly, with no standardized format\n- **Insurers** carry pricing risk during the extended binding cycle as market conditions change",
      "The fundamental issue is not that any single step is slow. It is that the entire chain is serial — each step waits for the previous one to complete — and the data format changes at every handoff.",
      "## What 'Instant' Actually Means",
      "The phrase 'instant insurance' can mean different things. In personal lines, it often means pre-underwritten products with simplified applications. In marine insurance, the assets are too complex and the exposures too large for that approach.",
      "What is achievable — and what the industry needs — is automated data flow from physical asset to pricing output. Not instant in the sense of zero processing time, but instant in the sense of eliminating the weeks of manual handoffs between inspection, scoring, valuation, and premium calculation.",
      "The pipeline looks like this:",
      "**Photo → Inspection Data (minutes).** Computer vision processes vessel imagery and generates structured condition findings. No scheduling. No site visit.",
      "**Inspection Data → Condition Score (seconds).** Automated scoring engine evaluates findings against maritime standards. Consistent output regardless of input source.",
      "**Condition Score → Valuation (seconds).** Market comparables, depreciation curves, and condition adjustment produce a defensible vessel value.",
      "**Valuation + Condition → Premium (seconds).** Deterministic pricing engine generates H&M and P&I premiums with full audit trail.",
      "Total elapsed time from photo upload to calculated premium: minutes, not weeks.",
      "## The Deterministic Difference",
      "Speed without accuracy is worse than being slow. The critical distinction in automated marine pricing is between probabilistic and deterministic approaches.",
      "A probabilistic approach uses machine learning to predict premiums based on historical patterns. It is fast, but it cannot explain its reasoning. When a reinsurer asks why a premium was set at a particular level, the answer is 'the model predicted it.'",
      "A deterministic approach uses defined rules: every variable is named, every weight is documented, every calculation step is traceable. The same inputs always produce the same output. When a reinsurer asks why, the answer is a complete audit trail.",
      "For regulated markets and sophisticated buyers, deterministic pricing is not optional. It is a requirement.",
      "## What Changes for the Market",
      "The compression of the binding cycle from weeks to minutes changes the economics of marine insurance in several ways:",
      "**Portfolio velocity.** Insurers can bind more policies with the same underwriting capacity. The bottleneck shifts from data processing to business development.",
      "**Pricing accuracy.** When premiums are calculated from current, verified condition data instead of stale survey reports, loss ratios improve. Well-maintained vessels pay less. Poorly-maintained vessels pay more. The market prices risk more efficiently.",
      "**Broker differentiation.** Brokers who can deliver structured, auditable vessel data will place business faster. Speed becomes a competitive advantage, not just a convenience.",
      "**Claims reduction.** When every policy is bound with a timestamped condition baseline, claims disputes decrease. The before-and-after evidence trail already exists.",
      "## The Infrastructure Layer",
      "None of this works without infrastructure. The marine insurance industry does not need another point solution for inspection or another AI model for pricing. It needs a connected system that moves data from physical asset to financial decision without manual intervention.",
      "This infrastructure layer — connecting vessel imagery to condition scores to valuations to premiums to claims baselines — is what transforms marine underwriting from an artisanal process to an engineered one.",
      "The technology is not theoretical. Every component described in this article exists today. The question is not whether the industry will adopt it, but which carriers, brokers, and MGAs will build the infrastructure first — and capture the competitive advantage that comes with it.",
    ],
  },
  {
    slug: "marine-insurance-digital-transformation",
    title: "Why marine insurance is the last frontier of digital transformation",
    description:
      "The marine insurance industry processes $34 billion in premiums using workflows designed in the 1980s. Here is why — and what is finally changing.",
    date: "2025-04-10",
    dateModified: "2026-05-01",
    category: "Industry",
    keywords: ["marine insurance digital transformation", "insurtech maritime", "marine underwriting modernization"],
    image:
      "https://res.cloudinary.com/drasbgjxe/image/upload/q_auto/f_auto/v1776652498/cargo-vision-inspection_yhxpc7.jpg",
    readTime: "7 min read",
    content: [
      "## A $34 Billion Industry Running on PDFs",
      "Marine insurance is one of the oldest commercial activities on earth. Lloyd's of London started in a coffee house in 1688. Three centuries later, the core workflow has barely changed: a broker assembles a submission package, a surveyor writes a narrative report, and an underwriter makes a decision based on experience and judgment.",
      "The numbers are staggering. The global marine insurance market generates over $34 billion in annual premiums. Yet the average time from submission to bound policy is 3 to 6 weeks. Claims settlement takes months. Documentation is fragmented across PDFs, emails, and spreadsheets.",
      "Every other insurance vertical has undergone digital transformation. Auto insurance uses telematics. Property insurance uses satellite imagery and IoT sensors. Health insurance runs on electronic medical records. Marine insurance still runs on paper.",
      "## Why Marine Lagged Behind",
      "The resistance to digitization is not laziness or ignorance. Marine insurance has structural characteristics that make transformation genuinely harder:",
      "**Asset complexity.** A cargo ship is not a car. It has thousands of structural components, operates in corrosive environments, and is subject to dozens of international regulatory frameworks. Standardizing the data capture for such a complex asset is a non-trivial engineering challenge.",
      "**Relationship-driven placement.** Marine insurance has operated on relationships for centuries. Brokers know underwriters. Underwriters trust surveyors. Disrupting these relationships requires delivering obvious, measurable value — not just a better user interface.",
      "**Regulatory fragmentation.** A vessel registered in Panama, insured in London, operating in the South China Sea, and classified by a Norwegian society is subject to four different regulatory frameworks simultaneously. Building technology that accounts for this fragmentation requires deep domain expertise.",
      "**Low frequency, high severity.** Marine claims are infrequent but large. A single hull loss can exceed $100 million. The stakes make the industry conservative about adopting unproven approaches.",
      "## What Changed",
      "Three developments have converged to make marine insurance digitization not just possible but inevitable:",
      "**Computer vision matured.** The same technology that powers autonomous vehicles can now analyze vessel imagery at scale. Hull damage that took surveyors days to document can be detected, classified, and scored in minutes.",
      "**Structured data infrastructure emerged.** The missing piece was never AI models — it was the infrastructure to move data from physical asset to financial decision. Inspection data needs to feed scoring engines, which feed valuation models, which feed pricing systems. Without this pipeline, AI models sit in isolation.",
      "**Regulatory pressure increased.** Classification societies and flag states are tightening documentation requirements. Insurers face growing pressure to demonstrate that their underwriting decisions are based on current, verifiable data — not outdated survey reports.",
      "## The Infrastructure Layer",
      "Digital transformation in marine insurance is not about replacing humans with algorithms. It is about building the data infrastructure that connects every step in the value chain: inspection to scoring to valuation to pricing to claims.",
      "When this infrastructure exists, human expertise becomes more valuable, not less. Underwriters can focus on judgment calls instead of data assembly. Surveyors can focus on complex cases instead of routine inspections. Brokers can differentiate on service quality instead of data availability.",
      "The question is no longer whether marine insurance will digitize. It is which organizations will build the infrastructure first — and capture the competitive advantage that comes with better data, faster decisions, and more accurate pricing.",
    ],
  },
  {
    slug: "general-average-explained",
    title: "General average explained: what every vessel owner needs to know",
    description:
      "General average is one of the oldest principles in maritime law — and one of the most misunderstood. Here is how it works and why it matters for your insurance.",
    date: "2025-04-22",
    dateModified: "2026-05-01",
    category: "Education",
    keywords: ["general average maritime law", "general average insurance", "vessel owner general average"],
    image:
      "https://res.cloudinary.com/drasbgjxe/image/upload/q_auto/f_auto/v1776652504/vessel-ai-assessment_dyupaw.jpg",
    readTime: "5 min read",
    content: [
      "## What Is General Average?",
      "General average is a principle of maritime law that predates modern insurance by centuries. The concept is simple: when cargo or equipment is deliberately sacrificed to save a vessel and its remaining cargo, the loss is shared proportionally among all parties with a financial interest in the voyage.",
      "If a captain orders containers thrown overboard during a storm to prevent the ship from capsizing, every cargo owner on board — not just the owner of the jettisoned containers — contributes to the loss. The contribution is calculated in proportion to the value of each party's interest in the voyage.",
      "## When General Average Is Declared",
      "General average is declared when three conditions are met:",
      "- **The sacrifice must be voluntary.** Accidental losses do not qualify. The captain must make a deliberate decision to sacrifice property for the common good.\n- **The sacrifice must be necessary.** There must be a genuine peril to the vessel and cargo. Jettisoning cargo for convenience does not qualify.\n- **The sacrifice must benefit the common venture.** The action must succeed in preserving the vessel and remaining cargo.",
      "In practice, general average is declared by the vessel owner, and an average adjuster is appointed to calculate how the loss is apportioned among all parties.",
      "## How Contributions Are Calculated",
      "An average adjuster calculates each party's contribution based on the value of their interest in the voyage at the destination port. If a vessel carries cargo from 50 different shippers, each shipper contributes in proportion to the value of their cargo relative to the total value of all cargo plus the vessel itself.",
      "**Example:** A vessel worth $10 million carries cargo worth $40 million total. If $2 million in cargo is jettisoned, the total loss ($2 million) is shared across the $50 million total interest. Each party pays 4% of their interest value. A shipper with $1 million in cargo contributes $40,000.",
      "## Why This Matters for Insurance",
      "Without marine cargo insurance, a shipper whose cargo survived a general average event still owes a contribution — potentially hundreds of thousands of dollars. Marine cargo insurance covers general average contributions, making it essential even for shippers who believe their cargo faces minimal direct risk.",
      "**Key implications:**",
      "**For vessel owners:** General average declarations trigger complex claims processes. Having timestamped condition baselines before and after the event accelerates settlement and reduces disputes.",
      "**For cargo owners:** Marine cargo insurance is not optional if you ship by sea. Even if your specific cargo is never damaged, a general average declaration makes you liable for a share of someone else's loss.",
      "**For insurers:** General average claims involve multiple parties, jurisdictions, and adjusters. Structured data and automated documentation reduce the administrative burden significantly.",
      "## The Modern Challenge",
      "General average events have become more complex as vessels have grown larger. A modern container ship carries cargo for thousands of shippers across dozens of countries. Calculating and collecting contributions from all parties can take years.",
      "The Ever Given grounding in the Suez Canal in 2021 resulted in one of the largest general average declarations in history. The vessel was carrying over 18,000 containers from thousands of cargo interests. The adjustment process involved calculating contributions for each individual shipment.",
      "Technology that captures vessel condition data in structured, timestamped formats before a voyage begins can dramatically simplify the general average adjustment process — reducing disputes, accelerating settlements, and providing the evidentiary foundation that all parties need.",
    ],
  },
  {
    slug: "hull-and-machinery-insurance-guide",
    title: "Hull & Machinery insurance: the complete guide for vessel operators",
    description:
      "Everything vessel operators need to know about H&M insurance — what it covers, how premiums are calculated, and how AI is changing the underwriting process.",
    date: "2025-05-01",
    dateModified: "2026-05-01",
    category: "Education",
    keywords: ["hull and machinery insurance", "H&M marine insurance", "vessel insurance coverage guide"],
    image:
      "https://res.cloudinary.com/drasbgjxe/image/upload/q_auto/f_auto/v1776652498/cargo-insurance-app_pgd9ga.jpg",
    readTime: "8 min read",
    content: [
      "## What Hull & Machinery Insurance Covers",
      "Hull & Machinery (H&M) insurance is one of the two primary classes of marine insurance, alongside Protection & Indemnity (P&I). H&M covers physical damage to the vessel itself — the hull structure, machinery, equipment, and fittings.",
      "Standard H&M coverage includes:",
      "- **Collision damage** — physical damage from contact with other vessels, fixed objects, or submerged hazards\n- **Grounding** — damage from running aground or striking the seabed\n- **Fire and explosion** — damage from onboard fires or machinery explosions\n- **Weather damage** — storm, heavy seas, and adverse weather conditions\n- **Machinery breakdown** — main engine, auxiliary engines, and onboard systems\n- **Sinking** — total loss from flooding or structural failure",
      "H&M insurance does NOT cover third-party liabilities (that is P&I), cargo damage, or losses from war, piracy, or nuclear events without specific endorsements.",
      "## How H&M Premiums Are Calculated",
      "H&M premiums are calculated as a percentage of the vessel's insured value. The rate depends on multiple factors:",
      "**Vessel condition.** This is the single largest factor. A vessel in excellent condition with no structural issues commands significantly lower premiums than one with deferred maintenance, corrosion, or machinery wear.",
      "**Vessel age and type.** Older vessels generally attract higher premiums due to increased mechanical risk and structural fatigue. Vessel type matters too — tankers, bulk carriers, and container ships each have different risk profiles.",
      "**Trading area.** Some regions carry higher risk due to weather patterns, piracy, congestion, or navigational hazards. Vessels operating in designated war zones require additional coverage.",
      "**Claims history.** A vessel or operator with a history of claims faces higher premiums. Conversely, a clean claims record over multiple years earns discounts.",
      "**Classification status.** Vessels classed with recognized classification societies (Lloyd's Register, DNV, Bureau Veritas, ABS) typically receive more favorable terms than unclassed or lapsed-class vessels.",
      "## The Agreed Value Problem",
      "Most H&M policies are written on an 'agreed value' basis — the insurer and insured agree on the vessel's value at the start of the policy. If the vessel is a total loss, the agreed value is what gets paid.",
      "The problem: agreed values often diverge from actual market values. If a vessel is insured for $5 million but is only worth $3 million at the time of loss, the insurer overpays. If insured for $3 million but worth $5 million, the owner is underinsured.",
      "Accurate, condition-based vessel valuation solves this problem. When the agreed value is derived from structured condition data, market comparables, and depreciation modeling, it reflects the vessel's actual worth — protecting both insurer and insured.",
      "## How AI Is Changing H&M Underwriting",
      "Traditional H&M underwriting relies on survey reports, broker submissions, and underwriter judgment. The process works, but it has limitations:",
      "**Data staleness.** By the time a survey report reaches an underwriter, the vessel's condition may have changed. The report reflects a point in time, not current reality.",
      "**Inconsistency.** Different surveyors document the same vessel differently. Underwriters must interpret narrative reports and make subjective judgments about condition severity.",
      "**Speed.** The submission-to-quote cycle takes weeks. Brokers assemble packages manually. Underwriters review them manually. Quotes are generated manually.",
      "AI-powered marine insurance infrastructure addresses all three limitations:",
      "**Current data.** Computer vision processes vessel imagery and generates structured condition findings in minutes, not weeks. The data is current when the underwriting decision is made.",
      "**Consistency.** Automated condition scoring applies the same criteria to every vessel. Findings are classified by type, severity, and extent using standardized frameworks.",
      "**Speed.** When condition data flows directly into scoring, valuation, and pricing engines, the submission-to-quote cycle compresses from weeks to minutes.",
      "## Choosing H&M Coverage",
      "When selecting H&M coverage, vessel operators should consider:",
      "**Insured value accuracy.** Ensure the agreed value reflects actual vessel condition and market value. Overinsurance wastes premium. Underinsurance creates unprotected exposure.",
      "**Deductible structure.** Higher deductibles reduce premiums but increase out-of-pocket costs for smaller claims. Match the deductible to your risk tolerance and cash flow.",
      "**Coverage extensions.** Standard H&M may not cover everything. Consider endorsements for machinery breakdown, loss of hire, crew negligence, and port risks based on your operating profile.",
      "**Classification maintenance.** Keep classification status current. Lapsed class status can void coverage or trigger premium surcharges.",
      "The marine insurance market is evolving. Operators who maintain structured, verifiable condition data on their vessels will increasingly access better terms, faster placement, and more accurate pricing. The data advantage is becoming a competitive advantage.",
    ],
  },
  {
    slug: "marine-insurance-claims-process",
    title: "The marine insurance claims process: from incident to settlement",
    description:
      "A step-by-step guide to marine insurance claims — what happens after an incident, how claims are assessed, and how technology is accelerating settlement.",
    date: "2025-05-15",
    dateModified: "2026-05-01",
    category: "Claims",
    keywords: ["marine insurance claims process", "vessel insurance claim", "maritime claims settlement"],
    image:
      "https://res.cloudinary.com/drasbgjxe/image/upload/q_auto/f_auto/v1776652504/vessel-ai-assessment_dyupaw.jpg",
    readTime: "6 min read",
    content: [
      "## When a Claim Begins",
      "A marine insurance claim begins the moment an incident occurs — collision, grounding, machinery failure, fire, or weather damage. The vessel operator must notify their insurer or broker immediately and take reasonable steps to prevent further loss.",
      "Prompt notification matters. Delayed reporting can complicate the claims process and, in some cases, provide grounds for insurers to dispute coverage. Most marine policies require notification within a specified timeframe, typically 24 to 72 hours.",
      "## The Claims Process Step by Step",
      "**Step 1: Incident notification.** The vessel operator contacts their broker or insurer. Initial information includes: nature of the incident, date and location, estimated severity, and immediate actions taken.",
      "**Step 2: Survey appointment.** The insurer appoints a surveyor to assess the damage. This may be a classification society surveyor, an independent marine surveyor, or the insurer's in-house expert. Survey timing depends on the vessel's location and the incident severity.",
      "**Step 3: Damage assessment.** The surveyor inspects the vessel, documents damage, and estimates repair costs. This is where the traditional process often breaks down — survey reports are narrative, subjective, and inconsistent between surveyors.",
      "**Step 4: Cause determination.** The insurer determines whether the damage falls within the policy's covered perils. Not all damage is covered. Pre-existing conditions, wear and tear, and excluded perils can reduce or void the claim.",
      "**Step 5: Repair authorization.** Once the claim is accepted, the insurer authorizes repairs. The vessel operator typically obtains competitive repair quotes. The insurer may require repairs at specific yards or by approved contractors.",
      "**Step 6: Settlement.** After repairs are completed and invoiced, the insurer calculates the settlement amount — repair costs minus the deductible, adjusted for any depreciation, betterment, or coverage limitations.",
      "## Why Claims Take So Long",
      "The average marine insurance claim takes 6 to 18 months from incident to settlement. Major claims can take years. The delays come from three sources:",
      "**Evidence gaps.** Without pre-loss baseline documentation, every claim becomes a dispute about the vessel's condition before the incident. Was that corrosion pre-existing? Was the machinery already worn? Without structured condition data, these questions are difficult to resolve.",
      "**Multi-party coordination.** Marine claims often involve multiple parties — vessel owner, insurer, reinsurer, classification society, repair yard, and potentially cargo interests. Coordinating between all parties adds time at every stage.",
      "**Documentation quality.** Narrative survey reports are open to interpretation. Two experts reviewing the same report may reach different conclusions about damage severity and repair requirements. Disputes over documentation consume months.",
      "## How Technology Accelerates Settlement",
      "The biggest opportunity in marine claims is not faster processing — it is better data at every stage:",
      "**Pre-loss baselines.** When a vessel's condition is documented in structured, timestamped format at the point of binding, the pre/post comparison becomes objective. There is no dispute about pre-existing conditions when both parties have access to the same baseline data.",
      "**Automated damage comparison.** Computer vision can compare post-incident imagery against stored baselines, identifying new damage and distinguishing it from pre-existing conditions. This reduces the subjectivity in damage assessment.",
      "**Structured repair estimates.** When damage is classified and quantified in structured format, repair cost estimation becomes more consistent. Repair yards can quote against specific, documented findings instead of interpreting narrative descriptions.",
      "**Evidence packaging.** Instead of assembling claims documentation manually, an automated system generates a complete evidence package — timestamped condition data, damage comparison, applicable standards, and repair estimates — in a format that all parties can review.",
      "## Best Practices for Vessel Operators",
      "Vessel operators can significantly improve their claims experience by:",
      "- **Documenting condition at bind.** Establish a structured condition baseline when the policy begins. This is the single most impactful step for accelerating future claims.\n- **Maintaining inspection records.** Regular condition documentation creates a timeline that supports claims and demonstrates maintenance diligence.\n- **Notifying promptly.** Contact your broker or insurer within hours of an incident, not days.\n- **Preserving evidence.** Photograph damage immediately. Do not begin repairs before the surveyor inspects unless necessary to prevent further loss.\n- **Understanding your coverage.** Know what your policy covers and what it excludes before an incident occurs.",
      "The marine insurance claims process is being transformed by technology — but the fundamentals remain the same. Document thoroughly, report promptly, and maintain your vessel. The data will take care of the rest.",
    ],
  },
]

export function getBlogPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug)
}

export function getAllBlogSlugs(): string[] {
  return blogPosts.map((p) => p.slug)
}
